# Generated by Django 4.2.3 on 2023-07-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_mode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusmode',
            name='default_music',
            field=models.CharField(choices=[('music1.mp3', 'Music 1'), ('music2.mp3', 'Music 2')], default='music1.mp3', max_length=255),
        ),
    ]
