# Generated by Django 4.0.5 on 2023-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_mode', '0002_focusmode_default_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusmode',
            name='duration',
            field=models.CharField(max_length=5),
        ),
    ]
